apiVersion: apps/v1
kind: Deployment
metadata:
  name: adminer
  labels:
    app: adminer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adminer
  template:
    metadata:
      labels:
        app: adminer
    spec:
      containers:
        - name: adminer
          image: adminer:latest
          ports:
            - containerPort: 8080
          env:
            - name: ADMINER_DEFAULT_SERVER
              value: "postgres-service"
            - name: ADMINER_DEFAULT_USERNAME
              value: "exampleuser"
            - name: ADMINER_DEFAULT_PASSWORD
              value: "examplepass"
      volumes:
        - name: adminer-data
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: adminer-service
  labels:
    app: adminer
spec:
  type: LoadBalancer
  ports:
    - port: 8081
      targetPort: 8080
  selector:
    app: adminer
