global:
  scrape_interval: 5s
scrape_configs:
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor-service.default.svc.cluster.local:8080']
  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana-service.default.svc.cluster.local:3000']