apiVersion: v1
kind: Secret
metadata:
  name: postgres-and-python-secret
  labels:
    app: postgres
type: Opaque
data:
  # Postgres credentials
  POSTGRES_USER: {{ .Values.postgres.env.POSTGRES_USER | b64enc | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgres.env.POSTGRES_PASSWORD | b64enc | quote }}
  POSTGRES_DB: {{ .Values.postgres.env.POSTGRES_DB | b64enc | quote }}

  # Application (Python Flask) database credentials
  DB_NAME: {{ .Values.pythonApp.env.DB_NAME | b64enc | quote }}
  DB_USER: {{ .Values.pythonApp.env.DB_USER | b64enc | quote }}
  DB_PASSWORD: {{ .Values.pythonApp.env.DB_PASSWORD | b64enc | quote }}
