FROM python:3.11-slim

WORKDIR /app
COPY . .

ENV PYTHONPATH=/app

RUN pip install --no-cache-dir \
    fastapi \
    uvicorn \
    sqlalchemy \
    psycopg2-binary \
    httpx \
    pytest \
    prometheus_client

CMD ["pytest", "--tb=short", "--disable-warnings"]
