FROM python:3.11-slim

WORKDIR /app
COPY . .

ENV PYTHONPATH=/app

RUN apt-get update && \
    apt-get install -y wget unzip default-jre && \
    wget https://github.com/allure-framework/allure2/releases/download/2.27.0/allure-2.27.0.tgz && \
    tar -xvzf allure-2.27.0.tgz && \
    mv allure-2.27.0 /opt/allure && \
    ln -s /opt/allure/bin/allure /usr/bin/allure && \
    rm allure-2.27.0.tgz

RUN pip install --no-cache-dir \
    fastapi \
    uvicorn \
    sqlalchemy \
    psycopg2-binary \
    httpx \
    pytest \
    allure-pytest \
    prometheus_client

CMD ["pytest", "--tb=short", "--disable-warnings"]
